# This isn't as full featured as the tox config, but tests the
# important stuff.

language: python

python:
  - 2.6
  - 2.7

install:
  - pip install --use-mirrors . Django==1.3.3

script:
  - nosetests -x tests -e test_django

notifications:
  email: false
